// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SharedEnums.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Com.Inferno.Protos {

  /// <summary>Holder for reflection information generated from SharedEnums.proto</summary>
  public static partial class SharedEnumsReflection {

    #region Descriptor
    /// <summary>File descriptor for SharedEnums.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SharedEnumsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFTaGFyZWRFbnVtcy5wcm90bxISY29tLmluZmVybm8ucHJvdG9zKmsKC1Jl",
            "cXVlc3RUeXBlEhAKDFJFUVVFU1RfTk9ORRAAEgsKB1NUQVJUVVAQARITCg9D",
            "UkVBVEVfTkVXX1VTRVIQAhITCg9MT0FEX1NUUlVDVFVSRVMQAxITCg9JTl9B",
            "UFBfUFVSQ0hBU0UQBCqRAQoMUmVzcG9uc2VUeXBlEhEKDVJFU1BPTlNFX05P",
            "TkUQABIUChBTVEFSVFVQX1JFU1BPTlNFEAESHAoYQ1JFQVRFX05FV19VU0VS",
            "X1JFU1BPTlNFEAISHAoYTE9BRF9TVFJVQ1RVUkVTX1JFU1BPTlNFEAMSHAoY",
            "SU5fQVBQX1BVUkNIQVNFX1JFU1BPTlNFEAQqUQoOUmVzcG9uc2VTdGF0dXMS",
            "GAoUUkVTUE9OU0VfU1RBVFVTX05PTkUQABILCgdTVUNDRVNTEAESCAoERkFJ",
            "TBACEg4KClVTRVJfRVhJU1QQA0INQgtTaGFyZWRFbnVtc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Com.Inferno.Protos.RequestType), typeof(global::Com.Inferno.Protos.ResponseType), typeof(global::Com.Inferno.Protos.ResponseStatus), }, null));
    }
    #endregion

  }
  #region Enums
  public enum RequestType {
    [pbr::OriginalName("REQUEST_NONE")] RequestNone = 0,
    [pbr::OriginalName("STARTUP")] Startup = 1,
    [pbr::OriginalName("CREATE_NEW_USER")] CreateNewUser = 2,
    [pbr::OriginalName("LOAD_STRUCTURES")] LoadStructures = 3,
    [pbr::OriginalName("IN_APP_PURCHASE")] InAppPurchase = 4,
  }

  public enum ResponseType {
    [pbr::OriginalName("RESPONSE_NONE")] ResponseNone = 0,
    [pbr::OriginalName("STARTUP_RESPONSE")] StartupResponse = 1,
    [pbr::OriginalName("CREATE_NEW_USER_RESPONSE")] CreateNewUserResponse = 2,
    [pbr::OriginalName("LOAD_STRUCTURES_RESPONSE")] LoadStructuresResponse = 3,
    [pbr::OriginalName("IN_APP_PURCHASE_RESPONSE")] InAppPurchaseResponse = 4,
  }

  public enum ResponseStatus {
    [pbr::OriginalName("RESPONSE_STATUS_NONE")] None = 0,
    [pbr::OriginalName("SUCCESS")] Success = 1,
    [pbr::OriginalName("FAIL")] Fail = 2,
    [pbr::OriginalName("USER_EXIST")] UserExist = 3,
  }

  #endregion

}

#endregion Designer generated code
